DM-45514: technote describing migration from `afw` types to new ShoeFits replacements
lsst-dm/dmtn-251 pull request #1
Opened 2024-08-07 17:18 UTC by TallJimbo

2024-10-31 21:00 UTC, parejkoj requested changes
Sorry it took me so long to finish this. A bunch of specific comments, but I'm not sure how to summarize my high level thoughts; I'll try here.

I haven't used mypy/Pydantic that much, and have often struggled with the "get an interface to work with mypy when not everything is explicitly typed" problem, which has probably made me more skeptical of it than is warranted. I think this proposal still feels a bit too much like magic to me, which means it may be hard for future users to understand, if they don't have a mypy background. I hope that is a much lower bar to jump over than understanding C++ templating, and I'm not sure whether it `shoefits` would result in a more, or less, transparent interface to pipeline users, compared with afw C++; I suspect more, given that the types would be inherently python, but I could see some Tasks taking rather complicated polymorphic inputs that might be hard to for a user to parse (see my existing trouble with `GetTemplateTask`'s "dict of lists of coadds" complexity).

I feel like it would be worth sharing this draft with the astropy ASDF folks, to get their opinions. I figure they've had a few different versions of "FITS serialization via ASDF" and might have some insights.

Inherently complicated systems are complicated, and there's probably no "easy" approach that would actually work, but I'm having trouble judging just how much of a win this would be over afw, other than the inherent "less C++, more python, blow up some of our old interfaces that we can't get rid of without a big 💥" improvement.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +In addition to the main ``image`` plane, it holds an integer ``mask`` plane of the same size (where each bit has a different interpretation) and a floating point ``variance`` plane that records the p
```suggestion
In addition to the main ``image`` plane, it holds an integer ``mask`` plane of the same size (where each bit corresponds to a particular mask field, e.g. `SATURATED`) and a floating point ``variance`` plane that records the per-pixel uncertainty (assuming it is uncorrelated).
```

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +ASDF-in-FITS is a little-used extension to the ASDF embeds the YAML tree and optional binary blocks into a FITS HDU as 1-d character image or binary table column.
```suggestion
ASDF-in-FITS is a little-used extension to the ASDF that embeds the YAML tree and optional binary blocks into a FITS HDU as a 1-d character image or binary table column.
```

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +This helps keep the ShoeFits library simple: it only needs to be able to read the files it writes, not arbitrary external FITS files, and for this it only needs to be able to read JSON (which it can
I feel like `and FITS binary data` is carrying a lot of weight here. If you mean "as opposed to headers", that doesn't seem like a huge win, given the various forms of "binary table", "binary image", and compressed versions of all the above. If you really just mean "FITS binary image data", then that seems like a much bigger advantage.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +These FITS header cards are *exported* from the Python object tree: they are never read when reconstructing a Python object hierarchy from the serialized form, and hence we expect to duplicate the he
Does this mean that the JSON tree will still be restricted to FITS-header representable things, e.g., <80chars, upper case keys, no NaN/inf (which have their own problems in JSON!), or can the FITS header export be not round-trippable?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +Objects serializable with ShoeFits are also by definition serializable as plain JSON, though in some cases this would be a very bad idea (e.g. a 4k x 4k image would have to be be represented as a nes
This seems to imply that we *wouldn't* want to serialize many of our objects with plain JSON? Is this paragraph really worth keeping? For which objects would this ability really be worth considering?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +These FITS-specific annotations would be ignored by any other `~lsst.shoefits.WriteContext` or `~lsst.shoefits.ReadContext` implementation, but for the FITS implementations they result in the ``array
```suggestion
These FITS-specific annotations would be ignored by any other `~lsst.shoefits.WriteContext` or `~lsst.shoefits.ReadContext` implementation, but for the FITS implementations they result in the ``array`` field being written to an image extension HDU with ``EXTNAME='DATA'``, and the ``instrument`` field's value written to a FITS header ``INSTRUME`` key.
```

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +        instrument: Annotated[str, shf.ExportFitsHeaderKey("INSTRUME")]
Implementation question: `FitsOptions` and `ExportFitsHeaderKey` aren't semantically close for me. Does it make sense to group all of the "how this gets save in FITS" options in a similar pseudo-namespace? For example, changing these to `FitsOptions`, `FitsExportHeaderKey` would help them be more readily discoverable and tie their "FITS-ness" together.

2024-10-31 21:00 UTC, parejkoj commented on example-layout.txt
> +    "byteorder": "big"
I don't see where these came from in the example in the text. Or is there a missing instantiation of the `Example` image type that would have specified this? That could be helpful.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +Any parent model type can now declare a field of type ``SerializableThing``, which will be a ``Thing`` instance at runtime and in static type checkers, while being transparently serializable via ``Th
Have you made a list of how many `Adapter` classes we'll need to serialize all of the things we currently write to our image files? I'm curious whether there would be a lot of these to implement, and whether any of them would be particularly complicated.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +- `~lsst.shoefits.Box` is analogous to `lsst.geom.Box2I`, but is not limited to two dimensions.
Why only `Box2I`, not `Box2D`? I find myself using the latter almost as much as the former.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +  It also has an optional `astropy.units.Unit`, allowing images with units to be saved via the ASDF ``Quantity`` data model.
Woo! `njy` images here we come!

Though, why make the unit optional?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +  Unlike its ``afw`` counterpart, `~lsst.shoefits.Mask` is backed by a 3-d array, with the last dimension used to support dynamic number of mask planes: typically the ``dtype`` of a `~lsst.shoefits.M
That dynamic length might be useful, but I wonder if it will cause extra headaches in both implementation and user problems. There are still uses for "get the bitmask and do bit-wise math on the Mask", and I'm not sure we could come up with a rich enough API for Mask to fully prevent that. I'm also not sure it's necessary, since we're just barely hitting the limits of 32-bit uint masks right now, and I suspect 64-bits would be more than enough. And mapping between a dynamic shoefits Mask and the afw fixed-bits one seems painful. Maybe there's some other context I'm missing here?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +Pydantic's `discriminated union <https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions>`__ functionality can be used to make this pattern much more efficient and robus (the default i
```suggestion
Pydantic's `discriminated union <https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions>`__ functionality can be used to make this pattern much more efficient and robust (the default implementation on read is to try all possibilities until one works).
```

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +The exact mechanism we'll use to solve this problem is TBD; ShoeFits tries to be agnostic to it, largely to avoid imposing any solution that might run afoul of security concerns (e.g. importing modul
I'm a little worried about this. I know we've sometimes had trouble with the existing measurement registries when someone didn't import the right package, and requiring it before a read seems definitely worrying. Do you have a few options you're considering for the TBD mechanism?

I worry that the potential flexibility gained by being able to define storage types elsewhere will be outweighed by the complexity added in import ordering from just requiring that all types be defined in shoefits directly.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +But neither ShoeFits nor Pydantic will actually check that objects loaded via the adaper registry actually inherit from ``Base``, so it's perfectly viable for the annotation to be a `typing.Protocol`
I'm not sure about the purpose of this sentence. What interface wouldn't be strongly typed? I thought the entire point of this design was to use strong typing to build the interface automatically?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +In addition to the complexity involved in setting up an adapter registry, the major disadvantage of `~lsst.shoefits.Polymorphic` is that there is no way to emit JSON schema for polymorphic fields, si
If we can't emit schema for those types, how do we actually use them in practice?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +ShoeFits mostly sidesteps the limitations of ``cfitsio`` in terms of reading from object stores by delegating to `astropy.io.fits` instead.
Is `astropy.io.fits` a requirement here, or could one substitute the python-based `fitsio` instead? I know that there are still cases where astropy fits is markedly slower, but maybe this system can avoid those?

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +Rust's libraries and toolchain for compiled Python extension modules will make it much easier (relative to C or C++) to set up the package and leverage third-party decompression code (for GZIP), with
```suggestion
Rust's libraries and toolchain for compiled Python extension modules will make it much easier (relative to C or C++) to set up the package and leverage third-party decompression code (for GZIP), without making it any harder to call small bits of vendored CFITSIO code if that becomes useful.
```

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +Rust's libraries and toolchain for compiled Python extension modules will make it much easier (relative to C or C++) to set up the package and leverage third-party decompression code (for GZIP), with
"ll small bits of vendored CFITSIO code if that becomes useful." - Now I'm sweating. I think we have to decide whether that is something we want to support in any way, or whether we want to fully avoid it. Though maybe you're thinking of small and specific enough examples that it would be mostly harmless?

"We built this tiny Rust library for handling in-memory compressed FITS blocks, but you also need cfitsio for these other three things, though we do all the important stuff in astropy.io.fits" doesn't seem like a good look.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +- I'd like each separate git package to have its own semver releases, with dependencies between packages handled by standard packaging tools like ``pip`` and ``conda``.
I think I like this part of the plan. It's already almost true for geom, sphgeom, and afw, given how slowly they evolve, so it feels like a reasonable ask.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +- I'd like to write a new low-level astronomical geometry library that combines the functionality in `lsst.sphgeom`, `lsst.geom`, and `lsst.afw.geom`, while improving consistency and avoiding subtle
[xkcd 927](http://xkcd.com/927/) rears its hydra-like head.

I hope this is very far down your schedule (or as far as it can be, given that it may be a requirement of a fully-working shoefits). Putting together our AST-based WCS in afw took Russell far longer than we initially expected. Maybe you'd be able to leverage much of that work so that this isn't as big of a project as it sounds like, but saying "we'll write a python/C API for astronomy primitives" (assuming your next paragraph, "move aware from C++" applies here) sounds like at least a year's worth of work, given past experience.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +  But I also think we should consider JIT-compilation tools like JAX and Numba as alternatives to C++ for algorithmic code, especially when something can be expressed via algorithmic primitives that
I have not looked at those tools for our use cases in several years, but I think the danger of going that direction is similar to the danger of relying on C++: it's hard to find enough developers with experience. Just having python experience doesn't mean that you can just wrap regular python in Numba and get a free win.

I'm not sure I have a good alternative proposal here, but thinking about *who* we can get to work on our code is probably one of the more important considerations in choosing tooling.

2024-10-31 21:00 UTC, parejkoj commented on index.rst
> +  I do expect that there will be cases where C++ will remain the best choice due to either history or the availability of certain third-party libraries, but I'd like to isolate and minimize these.
Same comment as above: is it easier or harder to find Rust developers in astronomy, as compared with C++ developers? How many Rust libraries are there that are as good as e.g. Eigen or GSL?

2024-10-31 21:00 UTC, parejkoj commented on example.py
> +#!/usr/bin/env python
Did you mean to include this example somewhere in the text? Maybe that's what I was missing regarding the details of the example fits file above?

2026-02-27 15:50 UTC, TallJimbo commented
I've added a commit that marks this technote deprecated in favor of RFC-1133, which remixes some of these ideas into a simpler package (still FITS + JSON and some brand new types, but a much less ambitious framework).  I'm then going to merge it so it can serve as a historical document.

@parejkoj , if you're still reading GitHub, thanks for your comments here.  I may not have ever gotten around to addressing them in this document, but they did help point me in a better direction with the superseding RFC.

2026-02-27 15:51 UTC, merged